mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: Gbw521314@
    database: gin-blog
    charset: utf8mb4
    log_level: "1"
    config: ""
logger:
    level: info
    prefix: DeMaster-GinBlog
    directory: ./logs
    show_line: true
    log_in_console: true
system:
    env: release
    host: 127.0.0.1
    port: "8085"
site_info:
    created_at: "2024-09-12"
    icp: 鄂ICP备2024040786号-1
    title: 呙博文的博客
    qq_image: https://masterde.top/qq_image
    wechat_image: https://masterde.top/wechat_image
    version: 1.0.01
    email: gthinkdesign520@gmail.com
    phone: 189-0867-9191
    name: DeMaster
    job: 项目经理/UI设计师
    addr: 湖北襄阳
    slogan: DeMaster
    slogan_en: DeMaster
    web: demaster.top
    github_url: gthinkdesign666@gmail.com
qq:
    app_id: "2424242"
    key: "2342424242"
    redirect: https://ru4fiibks.hn-bkt.clouddn.com/
qi_niu:
    access_key: 87It41LCRnj9XNzxnvP29IUitbqhrjvpxmM_HnPq
    secret_key: auE2u-0wpDrL1p9tcT0t9Y1i-6sNvgKx-FRHf_oN
    bucket: gbw-go-blog
    cdn: https://ru4fiibks.hn-bkt.clouddn.com/
    zone: z2
    size: 2
jwt:
    secret: 1LCRnj9XNzxnvP29IUitbqhrjvpxmM_HnPq
    expires: 0
    issuer: 1LCRnj9XNzxnvP29IUitbqhrjvpxmM_HnPq
email:
    host: 0.0.0.0
    port: 3000
    user: DeMaster
    password: '******'
    default_from_email: gthinkdesign520@gmail.com
    use_ssl: true
    user_tls: true
